workflow to sync the dist if yarn run v1.22.19 $ yarn workspaces run build
> @frontside/actions-utils
$ tsc --build
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/index.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/src/ansiColors.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/src/detectAffectedPackages.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/src/install.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/src/listAllPkgJsons.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/Users/jacobbolda/dev/github/thefrontside/actions/utils/dist/src/logIterable.d.ts' because it would overwrite input file.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. is missed